---
title: "Mean Begin"
author: "Haoran Zhang"
date: '2022-10-04'
output: html_document
---

```{r}
mean_B <- data.frame(Duration=double(),
                AIRG_B_1=double(),
                 Chol_B_1=double(),
                 DI_B_1=double(),
                 insIndex_B_1=double(),
                 Ins0_B_1=double(),
                 Ins30_B_1=double(),
                 DI30_B_1=double(),
                 SG_B_1=double(),
                 SI_B_1=double(),
                 AIRG_B_2=double(),
                 Chol_B_2=double(),
                 DI_B_2=double(),
                 insIndex_B_2=double(),
                 Ins0_B_2=double(),
                 Ins30_B_2=double(),
                 DI30_B_2=double(),
                 SG_B_2=double(),
                 SI_B_2=double(),
                 stringsAsFactors=FALSE)

mean_B[1,] <- c(mean(res_adjusted_mcc$Time,na.rm = TRUE),mean(res_adjusted_mcc$AIRG_B_1,na.rm = TRUE),mean(res_adjusted_mcc$Chol_B_1,na.rm = TRUE),mean(res_adjusted_mcc$DI_B_1,na.rm = TRUE),mean(res_adjusted_mcc$insIndex_B_1,na.rm = TRUE),mean(res_adjusted_mcc$Ins0_B_1,na.rm = TRUE),mean(res_adjusted_mcc$Ins30_B_1,na.rm = TRUE),mean(res_adjusted_mcc$DI30_B_1,na.rm = TRUE),mean(res_adjusted_mcc$SG_B_1,na.rm = TRUE),mean(res_adjusted_mcc$SI_B_1,na.rm = TRUE),
                             mean(res_adjusted_mcc$AIRG_B_2,na.rm = TRUE),mean(res_adjusted_mcc$Chol_B_2,na.rm = TRUE),mean(res_adjusted_mcc$DI_B_2,na.rm = TRUE),mean(res_adjusted_mcc$insIndex_B_2,na.rm = TRUE),mean(res_adjusted_mcc$Ins0_B_2,na.rm = TRUE),mean(res_adjusted_mcc$Ins30_B_2,na.rm = TRUE),mean(res_adjusted_mcc$DI30_B_2,na.rm = TRUE),mean(res_adjusted_mcc$SG_B_2,na.rm = TRUE),mean(res_adjusted_mcc$SI_B_2,na.rm = TRUE))

mean_B[2,] <- c(mean(res_adjusted_mcgg$Time,na.rm = TRUE),mean(res_adjusted_mcgg$AIRG_B_1,na.rm = TRUE),mean(res_adjusted_mcgg$Chol_B_1,na.rm = TRUE),mean(res_adjusted_mcgg$DI_B_1,na.rm = TRUE),mean(res_adjusted_mcgg$insIndex_B_1,na.rm = TRUE),mean(res_adjusted_mcgg$Ins0_B_1,na.rm = TRUE),mean(res_adjusted_mcgg$Ins30_B_1,na.rm = TRUE),mean(res_adjusted_mcgg$DI30_B_1,na.rm = TRUE),mean(res_adjusted_mcgg$SG_B_1,na.rm = TRUE),mean(res_adjusted_mcgg$SI_B_1,na.rm = TRUE),
                             mean(res_adjusted_mcgg$AIRG_B_2,na.rm = TRUE),mean(res_adjusted_mcgg$Chol_B_2,na.rm = TRUE),mean(res_adjusted_mcgg$DI_B_2,na.rm = TRUE),mean(res_adjusted_mcgg$insIndex_B_2,na.rm = TRUE),mean(res_adjusted_mcgg$Ins0_B_2,na.rm = TRUE),mean(res_adjusted_mcgg$Ins30_B_2,na.rm = TRUE),mean(res_adjusted_mcgg$DI30_B_2,na.rm = TRUE),mean(res_adjusted_mcgg$SG_B_2,na.rm = TRUE),mean(res_adjusted_mcgg$SI_B_2,na.rm = TRUE))

mean_B[3,] <- c(mean(as.numeric(res_adjusted_ccc$Time),na.rm = TRUE),mean(res_adjusted_ccc$AIRG_B_1,na.rm = TRUE),mean(res_adjusted_ccc$Chol_B_1,na.rm = TRUE),mean(res_adjusted_ccc$DI_B_1,na.rm = TRUE),mean(res_adjusted_ccc$insIndex_B_1,na.rm = TRUE),mean(res_adjusted_ccc$Ins0_B_1,na.rm = TRUE),mean(res_adjusted_ccc$Ins30_B_1,na.rm = TRUE),mean(res_adjusted_ccc$DI30_B_1,na.rm = TRUE),mean(res_adjusted_ccc$SG_B_1,na.rm = TRUE),mean(res_adjusted_ccc$SI_B_1,na.rm = TRUE),
                             mean(res_adjusted_ccc$AIRG_B_2,na.rm = TRUE),mean(res_adjusted_ccc$Chol_B_2,na.rm = TRUE),mean(res_adjusted_ccc$DI_B_2,na.rm = TRUE),mean(res_adjusted_ccc$insIndex_B_2,na.rm = TRUE),mean(res_adjusted_ccc$Ins0_B_2,na.rm = TRUE),mean(res_adjusted_ccc$Ins30_B_2,na.rm = TRUE),mean(res_adjusted_ccc$DI30_B_2,na.rm = TRUE),mean(res_adjusted_ccc$SG_B_2,na.rm = TRUE),mean(res_adjusted_ccc$SI_B_2,na.rm = TRUE))

mean_B[4,] <- c(mean(as.numeric(res_adjusted_ccgg$Time),na.rm = TRUE),mean(res_adjusted_ccgg$AIRG_B_1,na.rm = TRUE),mean(res_adjusted_ccgg$Chol_B_1,na.rm = TRUE),mean(res_adjusted_ccgg$DI_B_1,na.rm = TRUE),mean(res_adjusted_ccgg$insIndex_B_1,na.rm = TRUE),mean(res_adjusted_ccgg$Ins0_B_1,na.rm = TRUE),mean(res_adjusted_ccgg$Ins30_B_1,na.rm = TRUE),mean(res_adjusted_ccgg$DI30_B_1,na.rm = TRUE),mean(res_adjusted_ccgg$SG_B_1,na.rm = TRUE),mean(res_adjusted_ccgg$SI_B_1,na.rm = TRUE),
                             mean(res_adjusted_ccgg$AIRG_B_2,na.rm = TRUE),mean(res_adjusted_ccgg$Chol_B_2,na.rm = TRUE),mean(res_adjusted_ccgg$DI_B_2,na.rm = TRUE),mean(res_adjusted_ccgg$insIndex_B_2,na.rm = TRUE),mean(res_adjusted_ccgg$Ins0_B_2,na.rm = TRUE),mean(res_adjusted_ccgg$Ins30_B_2,na.rm = TRUE),mean(res_adjusted_ccgg$DI30_B_2,na.rm = TRUE),mean(res_adjusted_ccgg$SG_B_2,na.rm = TRUE),mean(res_adjusted_ccgg$SI_B_2,na.rm = TRUE))
rownames(mean_B)<-c("M_CC","M_CGG","C_CC","C_CGG")
```

```{r}
write.csv(mean_B,"mean.csv", row.names = FALSE)
```

