---
title: "time"
author: "Haoran Zhang"
date: '2022-10-01'
output: html_document
---

```{r}
library(RSQLite)
library(lubridate)
ivgtt<-dbConnect(RSQLite::SQLite(),"ivgtt.sqlite")
```


```{r}
Begin<-read.csv("Begin.csv")
Final<-read.csv("Final.csv")
Combine<-read.csv("Combine.csv")

dbWriteTable(ivgtt, "Begin", Begin, overwrite=TRUE)
dbWriteTable(ivgtt, "Final", Final, overwrite=TRUE)
dbWriteTable(ivgtt, "Combine", Combine, overwrite=TRUE)
```



```{sql,connection = ivgtt}
CREATE TABLE temp AS
SELECT * FROM Begin b INNER JOIN Final f on b.betageneId=f.betageneId
```

```{r}
temp<-dbReadTable(ivgtt, "temp", temp, overwrite=TRUE)
temp$IvgttDate<-as.Date(temp$IvgttDate,"%m/%d/%y")
temp$Date_B<-format(temp$IvgttDate,"%m/%d/%Y")
temp$Date_B<-as.Date(temp$Date_B,"%m/%d/%Y")
temp$Date_F<-as.Date(temp$Date_F,"%m/%d/%Y")
temp$Time<-difftime(temp$Date_B, temp$Date_F, units="auto")
write.csv(temp,"temp.csv", row.names = FALSE)
temp$Time<-temp$Time/365
```


```{r}
temp<-read.csv("temp.csv")

##Analysis 1: AGE+SEX
slope<-as.data.frame(cbind(temp$betageneId,temp$Time))
colnames(slope)<-c("ID","Time")

a1=lm(AIRG_B~ studyAge_B+ sex, data= temp, na.action=na.exclude)
AIRG_B_1= residuals(a1)+a1$coefficients[1]
slope = cbind(slope, AIRG_B_1)

a2=lm(Chol_B~ studyAge_B+ sex, data= temp, na.action=na.exclude)
Chol_B_1= residuals(a2)+a2$coefficients[1]
slope= cbind(slope,Chol_B_1)

a3=lm(DI_B~ studyAge_B+ sex, data= temp, na.action=na.exclude)
DI_B_1= residuals(a3)+a3$coefficients[1]
slope= cbind(slope,DI_B_1)

a4=lm(DI30_B~ studyAge_B+ sex, data= temp, na.action=na.exclude)
DI30_B_1= residuals(a4)+a4$coefficients[1]
slope= cbind(slope,DI30_B_1)

a5=lm(II_B~ studyAge_B+ sex, data= temp, na.action=na.exclude)
insIndex_B_1= residuals(a5)+a5$coefficients[1]
slope= cbind(slope,insIndex_B_1)

a6=lm(Ins0_B~ studyAge_B+ sex, data= temp, na.action=na.exclude)
Ins0_B_1= residuals(a6)+a6$coefficients[1]
slope= cbind(slope,Ins0_B_1)

a7=lm(Ins30_B~ studyAge_B+ sex, data= temp, na.action=na.exclude)
Ins30_B_1= residuals(a7)+a7$coefficients[1]
slope= cbind(slope,Ins30_B_1)

a8=lm(SG_B~ studyAge_B+ sex, data= temp, na.action=na.exclude)
SG_B_1= residuals(a8)+a8$coefficients[1]
slope= cbind(slope,SG_B_1)

a9=lm(SI_B~ studyAge_B+ sex, data= temp, na.action=na.exclude)
SI_B_1= residuals(a9)+a9$coefficients[1]
slope= cbind(slope,SI_B_1)
```

```{r}
##Analysis 2: AGE+SEX+BFP

b1=lm(AIRG_B~ studyAge_B+ sex +BFP_B, data= temp, na.action=na.exclude)
AIRG_B_2= residuals(b1)+b1$coefficients[1]
slope = cbind(slope, AIRG_B_2)

b2=lm(Chol_B~ studyAge_B+ sex+BFP_B, data= temp, na.action=na.exclude)
Chol_B_2= residuals(b2)+b2$coefficients[1]
slope= cbind(slope,Chol_B_2)

b3=lm(DI_B~ studyAge_B+ sex+BFP_B, data= temp, na.action=na.exclude)
DI_B_2= residuals(b3)+b3$coefficients[1]
slope= cbind(slope,DI_B_2)

b4=lm(DI30_B~ studyAge_B+ sex+BFP_B, data= temp, na.action=na.exclude)
DI30_B_2= residuals(b4)+b4$coefficients[1]
slope= cbind(slope,DI30_B_2)

b5=lm(II_B~ studyAge_B+ sex+BFP_B, data= temp, na.action=na.exclude)
insIndex_B_2= residuals(b5)+b5$coefficients[1]
slope= cbind(slope,insIndex_B_2)

b6=lm(Ins0_B~ studyAge_B+ sex+BFP_B, data= temp, na.action=na.exclude)
Ins0_B_2= residuals(b6)+b6$coefficients[1]
slope= cbind(slope,Ins0_B_2)

b7=lm(Ins30_B~ studyAge_B+ sex+BFP_B, data= temp, na.action=na.exclude)
Ins30_B_2= residuals(b7)+b7$coefficients[1]
slope= cbind(slope,Ins30_B_2)

b8=lm(SG_B~ studyAge_B+ sex+BFP_B, data= temp, na.action=na.exclude)
SG_B_2= residuals(b8)+b8$coefficients[1]
slope= cbind(slope,SG_B_2)

b9=lm(SI_B~ studyAge_B+ sex+BFP_B, data= temp, na.action=na.exclude)
SI_B_2= residuals(b9)+b9$coefficients[1]
slope= cbind(slope,SI_B_2)
```


```{r}
##Analysis 3: AGE+SEX Final
y1=lm(AIRG_F~ studyAge_F+ sex, data= temp, na.action=na.exclude)
AIRG_F_1= residuals(y1)+y1$coefficients[1]
slope = cbind(slope, AIRG_F_1)

y2=lm(Chol_F~ studyAge_F+ sex, data= temp, na.action=na.exclude)
Chol_F_1= residuals(y2)+y2$coefficients[1]
slope= cbind(slope,Chol_F_1)

y3=lm(DI_F~ studyAge_F+ sex, data= temp, na.action=na.exclude)
DI_F_1= residuals(y3)+y3$coefficients[1]
slope= cbind(slope,DI_F_1)

y4=lm(DI30_F~ studyAge_F+ sex, data= temp, na.action=na.exclude)
DI30_F_1= residuals(y4)+y4$coefficients[1]
slope= cbind(slope,DI30_F_1)

y5=lm(II_F~ studyAge_F+ sex, data= temp, na.action=na.exclude)
insIndex_F_1= residuals(y5)+y5$coefficients[1]
slope= cbind(slope,insIndex_F_1)

y6=lm(Ins0_F~ studyAge_F+ sex, data= temp, na.action=na.exclude)
Ins0_F_1= residuals(y6)+y6$coefficients[1]
slope= cbind(slope,Ins0_F_1)

y7=lm(Ins30_F~ studyAge_F+ sex, data= temp, na.action=na.exclude)
Ins30_F_1= residuals(y7)+y7$coefficients[1]
slope= cbind(slope,Ins30_F_1)

y8=lm(SG_F~ studyAge_F+ sex, data= temp, na.action=na.exclude)
SG_F_1= residuals(y8)+y8$coefficients[1]
slope= cbind(slope,SG_F_1)

y9=lm(SI_F~ studyAge_F+ sex, data= temp, na.action=na.exclude)
SI_F_1= residuals(y9)+y9$coefficients[1]
slope= cbind(slope,SI_F_1)
```

```{r}
##Analysis 4: AGE+SEX+BFP Final

z1=lm(AIRG_F~ studyAge_F+ sex+BFP_F, data= temp, na.action=na.exclude)
AIRG_F_2= residuals(z1)+z1$coefficients[1]
slope = cbind(slope, AIRG_F_2)

z2=lm(Chol_F~ studyAge_F+ sex+BFP_F, data= temp, na.action=na.exclude)
Chol_F_2= residuals(z2)+z2$coefficients[1]
slope= cbind(slope,Chol_F_2)

z3=lm(DI_F~ studyAge_F+ sex+BFP_F, data= temp, na.action=na.exclude)
DI_F_2= residuals(z3)+z3$coefficients[1]
slope= cbind(slope,DI_F_2)

z4=lm(DI30_F~ studyAge_F+ sex+BFP_F, data= temp, na.action=na.exclude)
DI30_F_2= residuals(z4)+z4$coefficients[1]
slope= cbind(slope,DI30_F_2)

z5=lm(II_F~ studyAge_F+ sex+BFP_F, data= temp, na.action=na.exclude)
insIndex_F_2= residuals(z5)+z5$coefficients[1]
slope= cbind(slope,insIndex_F_2)

z6=lm(Ins0_F~ studyAge_F+ sex+BFP_F, data= temp, na.action=na.exclude)
Ins0_F_2= residuals(z6)+z6$coefficients[1]
slope= cbind(slope,Ins0_F_2)

z7=lm(Ins30_F~ studyAge_F+ sex+BFP_F, data= temp, na.action=na.exclude)
Ins30_F_2= residuals(z7)+z7$coefficients[1]
slope= cbind(slope,Ins30_F_2)

z8=lm(SG_F~ studyAge_F+ sex+BFP_F, data= temp, na.action=na.exclude)
SG_F_2= residuals(y8)+y8$coefficients[1]
slope= cbind(slope,SG_F_2)

z9=lm(SI_F~ studyAge_F+ sex+BFP_F, data= temp, na.action=na.exclude)
SI_F_2= residuals(z9)+z9$coefficients[1]
slope= cbind(slope,SI_F_2)
```



```{sql,connection = ivgtt}
CREATE TABLE MCC AS
SELECT * FROM temp t INNER JOIN Combine c on t.betageneId=ID WHERE c.MTNR1B=0
```


