---
title: "Untitled"
author: "Haoran Zhang"
date: '2023-01-26'
output: html_document
---

```{r}
##Analysis 1: AGE+SEX
C_reg<-C_all["ID"]

a1=lm(AIRG_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
AIRG_1= a1$coefficients[1]+a1$coefficients[2]*C_all$CDKAL1

a1=lm(AIRG_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
AIRG_1=a1$coefficients[1]+a1$coefficients[2]*C_all$CDKAL1
C_reg = cbind(C_reg, AIRG_1)

a2=lm(Chol_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
Chol_1= a2$coefficients[1]+a2$coefficients[2]*C_all$CDKAL1
C_reg= cbind(C_reg,Chol_1)

a3=lm(DI_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
DI_1= a3$coefficients[1]+a3$coefficients[2]*C_all$CDKAL1
C_reg= cbind(C_reg,DI_1)

a4=lm(DI30_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
DI30_1= a4$coefficients[1]+a4$coefficients[2]*C_all$CDKAL1
C_reg= cbind(C_reg,DI30_1)

a5=lm(II_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
insIndex_1= a5$coefficients[1]+a5$coefficients[2]*C_all$CDKAL1
C_reg= cbind(C_reg,insIndex_1)

a6=lm(Ins0_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
Ins0_1= a6$coefficients[1]+a6$coefficients[2]*C_all$CDKAL1
C_reg= cbind(C_reg,Ins0_1)

a7=lm(Ins30_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
Ins30_1= a7$coefficients[1]+a7$coefficients[2]*C_all$CDKAL1
C_reg= cbind(C_reg,Ins30_1)

a8=lm(SG_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
SG_1= a8$coefficients[1]+a8$coefficients[2]*C_all$CDKAL1
C_reg= cbind(C_reg,SG_1)

a9=lm(SI_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
SI_1= a9$coefficients[1]+a9$coefficients[2]*C_all$CDKAL1
C_reg= cbind(C_reg,SI_1)
```

```{r}
b1=lm(AIRG_2/Time~ CDKAL1, data= C_all, na.action=na.exclude)
AIRG_2= b1$coefficients[1]+b1$coefficients[2]*C_all$CDKAL1
C_reg = cbind(C_reg, AIRG_2)

b2=lm(Chol_2/Time~ CDKAL1, data= C_all, na.action=na.exclude)
Chol_2= b2$coefficients[1]+b2$coefficients[2]*C_all$CDKAL1
C_reg= cbind(C_reg,Chol_2)

b3=lm(DI_2/Time~ CDKAL1, data= C_all, na.action=na.exclude)
DI_2= b3$coefficients[1]+b3$coefficients[2]*C_all$CDKAL1
C_reg= cbind(C_reg,DI_2)

b4=lm(DI30_2/Time~ CDKAL1, data= C_all, na.action=na.exclude)
DI30_2= b4$coefficients[1]+b4$coefficients[2]*C_all$CDKAL1
C_reg= cbind(C_reg,DI30_2)

b5=lm(II_2/Time~ CDKAL1, data= C_all, na.action=na.exclude)
insIndex_2= b5$coefficients[1]+b5$coefficients[2]*C_all$CDKAL1
C_reg= cbind(C_reg,insIndex_2)

b6=lm(Ins0_2/Time~ CDKAL1, data= C_all, na.action=na.exclude)
Ins0_2= b6$coefficients[1]+b6$coefficients[2]*C_all$CDKAL1
C_reg= cbind(C_reg,Ins0_2)

b7=lm(Ins30_2/Time~ CDKAL1, data= C_all, na.action=na.exclude)
Ins30_2= b7$coefficients[1]+b7$coefficients[2]*C_all$CDKAL1
C_reg= cbind(C_reg,Ins30_2)

b8=lm(SG_2/Time~ CDKAL1, data= C_all, na.action=na.exclude)
SG_2= b8$coefficients[1]+b8$coefficients[2]*C_all$CDKAL1
C_reg= cbind(C_reg,SG_2)

b9=lm(SI_2/Time~ CDKAL1, data= C_all, na.action=na.exclude)
SI_2= b9$coefficients[1]+b9$coefficients[2]*C_all$CDKAL1
C_reg= cbind(C_reg,SI_2)
```


```{r}
##Analysis 1: AGE+SEX
M_reg<-M_all["ID"]

##Analysis 1: AGE+SEX
#M_reg<-as.data.frame(cbind(ccg$betageneId, ccg$Date_B, ccg$Date_F, ccg$Time, ccg$MTNR1B, ccg$CDKAL1))
#colnames(M_reg)<-c("ID", "Date_B", "Date_F", "Time", "MTNR1B", "CDKAL1")


x1=lm(AIRG_1/Time~ MTNR1B, data= M_all, na.action=na.exclude)
AIRG_1= x1$coefficients[1]+x1$coefficients[2]*M_all$MTNR1B
M_reg = cbind(M_reg, AIRG_1)

x2=lm(Chol_1/Time~ MTNR1B, data= M_all, na.action=na.exclude)
Chol_1= x2$coefficients[1]+x2$coefficients[2]*M_all$MTNR1B
M_reg= cbind(M_reg,Chol_1)

x3=lm(DI_1/Time~ MTNR1B, data= M_all, na.action=na.exclude)
DI_1= x3$coefficients[1]+x3$coefficients[2]*M_all$MTNR1B
M_reg= cbind(M_reg,DI_1)

x4=lm(DI30_1/Time~ MTNR1B, data= M_all, na.action=na.exclude)
DI30_1= x4$coefficients[1]+x4$coefficients[2]*M_all$MTNR1B
M_reg= cbind(M_reg,DI30_1)

x5=lm(II_1/Time~ MTNR1B, data= M_all, na.action=na.exclude)
insIndex_1= x5$coefficients[1]+x5$coefficients[2]*M_all$MTNR1B
M_reg= cbind(M_reg,insIndex_1)

x6=lm(Ins0_1/Time~ MTNR1B, data= M_all, na.action=na.exclude)
Ins0_1= x6$coefficients[1]+x6$coefficients[2]*M_all$MTNR1B
M_reg= cbind(M_reg,Ins0_1)

x7=lm(Ins30_1/Time~ MTNR1B, data= M_all, na.action=na.exclude)
Ins30_1= x7$coefficients[1]+x7$coefficients[2]*M_all$MTNR1B
M_reg= cbind(M_reg,Ins30_1)

x8=lm(SG_1/Time~ MTNR1B, data= M_all, na.action=na.exclude)
SG_1= x8$coefficients[1]+x8$coefficients[2]*M_all$MTNR1B
M_reg= cbind(M_reg,SG_1)

x9=lm(SI_1/Time~ MTNR1B, data= M_all, na.action=na.exclude)
SI_1= x9$coefficients[1]+x9$coefficients[2]*M_all$MTNR1B
M_reg= cbind(M_reg,SI_1)
```

```{r}
y1=lm(AIRG_2/Time~ MTNR1B, data= M_all, na.action=na.exclude)
AIRG_2= y1$coefficients[1]+y1$coefficients[2]*M_all$MTNR1B
M_reg = cbind(M_reg, AIRG_2)

y2=lm(Chol_2/Time~ MTNR1B, data= M_all, na.action=na.exclude)
Chol_2= y2$coefficients[1]+y2$coefficients[2]*M_all$MTNR1B
M_reg= cbind(M_reg,Chol_2)

y3=lm(DI_2/Time~ MTNR1B, data= M_all, na.action=na.exclude)
DI_2= y3$coefficients[1]+y3$coefficients[2]*M_all$MTNR1B
M_reg= cbind(M_reg,DI_2)

y4=lm(DI30_2/Time~ MTNR1B, data= M_all, na.action=na.exclude)
DI30_2= y4$coefficients[1]+y4$coefficients[2]*M_all$MTNR1B
M_reg= cbind(M_reg,DI30_2)

y5=lm(II_2/Time~ MTNR1B, data= M_all, na.action=na.exclude)
insIndex_2= y5$coefficients[1]+y5$coefficients[2]*M_all$MTNR1B
M_reg= cbind(M_reg,insIndex_2)

y6=lm(Ins0_2/Time~ MTNR1B, data= M_all, na.action=na.exclude)
Ins0_2= y6$coefficients[1]+y6$coefficients[2]*M_all$MTNR1B
M_reg= cbind(M_reg,Ins0_2)

y7=lm(Ins30_2/Time~ MTNR1B, data= M_all, na.action=na.exclude)
Ins30_2= y7$coefficients[1]+y7$coefficients[2]*M_all$MTNR1B
M_reg= cbind(M_reg,Ins30_2)

y8=lm(SG_2/Time~ MTNR1B, data= M_all, na.action=na.exclude)
SG_2= y8$coefficients[1]+y8$coefficients[2]*M_all$MTNR1B
M_reg= cbind(M_reg,SG_2)

y9=lm(SI_2/Time~ MTNR1B, data= M_all, na.action=na.exclude)
SI_2= y9$coefficients[1]+y9$coefficients[2]*M_all$MTNR1B
M_reg= cbind(M_reg,SI_2)
```




```{r}
##Analysis 1: AGE+SEX
C_reg<-C_all["ID"]

##Analysis 1: AGE+SEX
#C_reg<-as.data.frame(cbind(ccg$betageneId, ccg$Date_B, ccg$Date_F, ccg$Time, ccg$CDKAL1, ccg$CDKAL1))
#colnames(C_reg)<-c("ID", "Date_B", "Date_F", "Time", "CDKAL1", "CDKAL1")

#a1=lm(AIRG_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
#AIRG_1= a1$coefficients[1]+a1$coefficients[2]*C_all$CDKAL1

a1=lm(AIRG_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
AIRG_1= residuals(a1)+a1$coefficients[1]
C_reg = cbind(C_reg, AIRG_1)

a2=lm(Chol_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
Chol_1= residuals(a2)+a2$coefficients[1]
C_reg= cbind(C_reg,Chol_1)

a3=lm(DI_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
DI_1= residuals(a3)+a3$coefficients[1]
C_reg= cbind(C_reg,DI_1)

a4=lm(DI30_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
DI30_1= residuals(a4)+a4$coefficients[1]
C_reg= cbind(C_reg,DI30_1)

a5=lm(II_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
insIndex_1= residuals(a5)+a5$coefficients[1]
C_reg= cbind(C_reg,insIndex_1)

a6=lm(Ins0_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
Ins0_1= residuals(a6)+a6$coefficients[1]
C_reg= cbind(C_reg,Ins0_1)

a7=lm(Ins30_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
Ins30_1= residuals(a7)+a7$coefficients[1]
C_reg= cbind(C_reg,Ins30_1)

a8=lm(SG_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
SG_1= residuals(a8)+a8$coefficients[1]
C_reg= cbind(C_reg,SG_1)

a9=lm(SI_1/Time~ CDKAL1, data= C_all, na.action=na.exclude)
SI_1= residuals(a9)+a9$coefficients[1]
C_reg= cbind(C_reg,SI_1)
```

```{r}
b1=lm(AIRG_2/Time~ CDKAL1, data= C_all, na.action=na.exclude)
AIRG_2= residuals(b1)+b1$coefficients[1]
C_reg = cbind(C_reg, AIRG_2)

b2=lm(Chol_2/Time~ CDKAL1, data= C_all, na.action=na.exclude)
Chol_2= residuals(b2)+b2$coefficients[1]
C_reg= cbind(C_reg,Chol_2)

b3=lm(DI_2/Time~ CDKAL1, data= C_all, na.action=na.exclude)
DI_2= residuals(b3)+b3$coefficients[1]
C_reg= cbind(C_reg,DI_2)

b4=lm(DI30_2/Time~ CDKAL1, data= C_all, na.action=na.exclude)
DI30_2= residuals(b4)+b4$coefficients[1]
C_reg= cbind(C_reg,DI30_2)

b5=lm(II_2/Time~ CDKAL1, data= C_all, na.action=na.exclude)
insIndex_2= residuals(b5)+b5$coefficients[1]
C_reg= cbind(C_reg,insIndex_2)

b6=lm(Ins0_2/Time~ CDKAL1, data= C_all, na.action=na.exclude)
Ins0_2= residuals(b6)+b6$coefficients[1]
C_reg= cbind(C_reg,Ins0_2)

b7=lm(Ins30_2/Time~ CDKAL1, data= C_all, na.action=na.exclude)
Ins30_2= residuals(b7)+b7$coefficients[1]
C_reg= cbind(C_reg,Ins30_2)

b8=lm(SG_2/Time~ CDKAL1, data= C_all, na.action=na.exclude)
SG_2= residuals(b8)+b8$coefficients[1]
C_reg= cbind(C_reg,SG_2)

b9=lm(SI_2/Time~ CDKAL1, data= C_all, na.action=na.exclude)
SI_2= residuals(b9)+b9$coefficients[1]
C_reg= cbind(C_reg,SI_2)
```


```{r}
##Analysis 1: AGE+SEX
M_reg<-M_all["ID"]

##Analysis 1: AGE+SEX
#M_reg<-as.data.frame(cbind(ccg$betageneId, ccg$Date_B, ccg$Date_F, ccg$Time, ccg$MTNR1B, ccg$CDKAL1))
#colnames(M_reg)<-c("ID", "Date_B", "Date_F", "Time", "MTNR1B", "CDKAL1")


x1=lm(AIRG_1/Time~ MTNR1B, data= M_all, na.action=na.exclude)
AIRG_1= residuals(x1)+x1$coefficients[1]
M_reg = cbind(M_reg, AIRG_1)

x2=lm(Chol_1/Time~ MTNR1B, data= M_all, na.action=na.exclude)
Chol_1= residuals(x2)+x2$coefficients[1]
M_reg= cbind(M_reg,Chol_1)

x3=lm(DI_1/Time~ MTNR1B, data= M_all, na.action=na.exclude)
DI_1= residuals(x3)+x3$coefficients[1]
M_reg= cbind(M_reg,DI_1)

x4=lm(DI30_1/Time~ MTNR1B, data= M_all, na.action=na.exclude)
DI30_1= residuals(x4)+x4$coefficients[1]
M_reg= cbind(M_reg,DI30_1)

x5=lm(II_1/Time~ MTNR1B, data= M_all, na.action=na.exclude)
insIndex_1= residuals(x5)+x5$coefficients[1]
M_reg= cbind(M_reg,insIndex_1)

x6=lm(Ins0_1/Time~ MTNR1B, data= M_all, na.action=na.exclude)
Ins0_1= residuals(x6)+x6$coefficients[1]
M_reg= cbind(M_reg,Ins0_1)

x7=lm(Ins30_1/Time~ MTNR1B, data= M_all, na.action=na.exclude)
Ins30_1= residuals(x7)+x7$coefficients[1]
M_reg= cbind(M_reg,Ins30_1)

x8=lm(SG_1/Time~ MTNR1B, data= M_all, na.action=na.exclude)
SG_1= residuals(x8)+x8$coefficients[1]
M_reg= cbind(M_reg,SG_1)

x9=lm(SI_1/Time~ MTNR1B, data= M_all, na.action=na.exclude)
SI_1= residuals(x9)+x9$coefficients[1]
M_reg= cbind(M_reg,SI_1)
```

```{r}
y1=lm(AIRG_2/Time~ MTNR1B, data= M_all, na.action=na.exclude)
AIRG_2= residuals(y1)+y1$coefficients[1]
M_reg = cbind(M_reg, AIRG_2)

y2=lm(Chol_2/Time~ MTNR1B, data= M_all, na.action=na.exclude)
Chol_2= residuals(y2)+y2$coefficients[1]
M_reg= cbind(M_reg,Chol_2)

y3=lm(DI_2/Time~ MTNR1B, data= M_all, na.action=na.exclude)
DI_2= residuals(y3)+y3$coefficients[1]
M_reg= cbind(M_reg,DI_2)

y4=lm(DI30_2/Time~ MTNR1B, data= M_all, na.action=na.exclude)
DI30_2= residuals(y4)+y4$coefficients[1]
M_reg= cbind(M_reg,DI30_2)

y5=lm(II_2/Time~ MTNR1B, data= M_all, na.action=na.exclude)
insIndex_2= residuals(y5)+y5$coefficients[1]
M_reg= cbind(M_reg,insIndex_2)

y6=lm(Ins0_2/Time~ MTNR1B, data= M_all, na.action=na.exclude)
Ins0_2= residuals(y6)+y6$coefficients[1]
M_reg= cbind(M_reg,Ins0_2)

y7=lm(Ins30_2/Time~ MTNR1B, data= M_all, na.action=na.exclude)
Ins30_2= residuals(y7)+y7$coefficients[1]
M_reg= cbind(M_reg,Ins30_2)

y8=lm(SG_2/Time~ MTNR1B, data= M_all, na.action=na.exclude)
SG_2= residuals(y8)+y8$coefficients[1]
M_reg= cbind(M_reg,SG_2)

y9=lm(SI_2/Time~ MTNR1B, data= M_all, na.action=na.exclude)
SI_2= residuals(y9)+y9$coefficients[1]
M_reg= cbind(M_reg,SI_2)
```